services:
  jekyll:
    image: ruby:3.1
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --baseurl '' --config _config.yml"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
